### ISSUE TITLE
Add phpcs

### ISSUE THREAD

**Issue by Gman98ish** [ukfast/sdk-php#3]
## Overview

Would be good to get code standards consistent and enforced. The code is currently all PSR2, but would be good to get phpcs added to dev dependencies, and get a CI process up to enforce it.

**Comment by gavtaylor** [comment]
added in https://github.com/ukfast/sdk-php/commit/38a1183680b7246d1dd7f0f6902d3d0f416f8c27

**Comment by gavtaylor** [comment]
travis ci added, see https://github.com/ukfast/sdk-php/pull/7
